%macro pushaq 0
  pushfq
  push rax
  push rbx
  push rcx
  push rdx
  push rbp
  push rsi
  push rdi
  push r8
  push r9
  push r10
  push r11
  push r12
  push r13
  push r14
  push r15
%endmacro

%macro popaq 0
  pop r15
  pop r14
  pop r13
  pop r12
  pop r11
  pop r10
  pop r9
  pop r8
  pop rdi
  pop rsi
  pop rbp
  pop rdx
  pop rcx
  pop rbx
  pop rax
  popfq
%endmacro

%define BREAKPOINT xchg bx, bx

%macro releasePic 1
  extern pic_eoi
  mov dl, %1
  call pic_eoi
%endmacro

